### ISSUE TITLE
[1.15.2] Can't pick up chunk loader in survival

### ISSUE THREAD

**Issue by ocram9** [codetaylor/chunkt#3]
When I try to remove the chunk loader with a pickaxe it doesn't drop it.

 **Versions**
- Minecraft 1.15.2
- Forge 31.1.37
- Chunkt 1.0.2

**Comment by codetaylor** [comment]
Oops! Thanks for the report.

I'll get this fixed up first thing tomorrow. :)

**Comment by ocram9** [comment]
No problem! Take your time :D
