### ISSUE TITLE
[1.15.2] Conflict with mod: Performant

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/chunkt#4]
> I don't think I have the exact same issue as @systemshaper seems to have but my server also can't start with this mod loaded (it works if I remove the mod). I'm on 1.15.2 and a different forge version (31.1.37) so I don't know if that is the issue here. My server just crashes though, I don't even have the option to join. This also started happening to me after I placed chunk loaders and then restarted.
>
> I know very little about coding/modding so I could be wrong but if I just skim over the crash log it seems to be mixin incompatibility maybe?
>
> Latest log:
https://gist.github.com/ocram9/58979c9acd001c83515589db876e7518
>
> Crash log:
https://gist.github.com/ocram9/2090bdc580613c49e8ad5e182e64f4d0

**Comment by codetaylor** [comment]
So it looks like the mod `performant-1.15-2.0m` has a mixin that is conflicting with Chunkt's access transformer.

Chunkt's access transformer sets the method `func_219243_d` to public level visibility and the performant mixin `world.chunk.ChunkManagerMixin` overwrites the method with a package level visibility.

```
PACKAGE @Overwrite method func_219243_d in performant.mixins.json:world.chunk.ChunkManagerMixin cannot reduce visibiliy of PUBLIC target method
```

![image](https://user-images.githubusercontent.com/1240716/78580944-08ae9a80-77e8-11ea-9487-c939f47d03db.png)

I don't know how to solve this yet.

Edit:
https://www.curseforge.com/minecraft/mc-mods/performant

**Comment by ocram9** [comment]
I have just reported a bug with performant too (it's an issue with the nether). I'm not sure if they are related in any way but I had to downgrade performant to an older version. I'll check if that fixed the compatibility issue with your mod.

[https://github.com/ldtteam/Performant/issues/24](url)

**Comment by ocram9** [comment]
Downgrading to a previous version of Performant (performant-1.15-1.12) did fix the issue so it seems to be only affecting the newest version. I'll wait until the Performant nether fix to see if that fixes this issue as well.

**Comment by ocram9** [comment]
The Performant nether bug has been fixed but sadly didn't fix the compatibility with this mod. I'll leave Performant downgraded for now. Is this issue fixable on your end or should I contact the Performant devs?

**Comment by codetaylor** [comment]
It will be fixed in the next release.

**Comment by ocram9** [comment]
Awesome! Thank you :)

**Comment by ocram9** [comment]
Performant just had an update again and that has fixed the issue: https://github.com/ldtteam/Performant/issues/25

Not sure if this changes anything about your fix but I thought I'd let you know

**Comment by codetaylor** [comment]
Thanks.

Sure, it will fix the Performant compat with Chunkt, but as long as Chunkt uses AT's to elevate the visibility of the method in question, Chunkt would continue to conflict with any other mod that does something similar to what Performant did. Now that Performant has changed the visibility of the method, Performant could now potentially suffer the same conflict with other mods.

The best solution for Chunkt is to remove its dependence on AT. This dependence has already been removed in the 1.14 version and will be in the next 1.15 version.
